variable "team_name" {}
variable "cluster_name" {}
variable "vpc_id" {}
variable "dedicated_resource_account_role" {}
variable "enable_subnet_share" {}
variable "dedicated_security_group_enable" {}
variable "network_policy_enable" {}
variable "allowed_rules_in_dev_namespace" {}
variable "allowed_rules_in_ops_namespace" {}
variable "dedicated_resource_account" {}
variable "additional_security_groups" {}
variable "additional_security_groups_k8s_configuration" {}
variable "team_jenkins_service_account_name" {}
variable "permissive_rbac_dev" {}
variable "permissive_rbac_ops" {}
variable "extended_rbac_rules_dev" {}
variable "extended_rbac_rules_ops" {}
variable "additional_sc_groups" {}