apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: ps-tools-prod-12042021
  namespace: velero
spec:
  schedule: "0 2 * * *" #every day at 2 AM
  template:
    hooks: {}
    includedNamespaces:
    - ps-tools-prod-dev
    - ps-tools-prod-ops
    storageLocation: aws
    ttl: 288h #2 weeks