apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calico.yaml

images:
- name: quay.io/calico/node
  newTag: v3.21.4

- name: quay.io/calico/typha 
  newTag: v3.21.4







