apiVersion: v1
data:
  subscriptions: |
    - recipients:
      - slack:ext-supercell-notifications
      triggers:
      - on-sync-failed
      - on-health-degraded
    - recipients:
      - slack:ext-supercell-notifications
      triggers:
      - on-deployed
  context: |
    clusterRegion: cn-northwest-1
    clusterName: eks-02-prod-china
    argocdUrl: "https://localhost:8843/"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: argocd-notifications-cm