apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
      - name: dex
        image: 508085692393.dkr.ecr.cn-northwest-1.amazonaws.com.cn/mirror/ghcr.io/dexidp/dex:v2.27.0
      initContainers:
      - name: copyutil
        image: 508085692393.dkr.ecr.cn-northwest-1.amazonaws.com.cn/mirror/argoproj/argocd:v1.8.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        image: 508085692393.dkr.ecr.cn-northwest-1.amazonaws.com.cn/mirror/argoproj/argocd:v1.8.2
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        image: 508085692393.dkr.ecr.cn-northwest-1.amazonaws.com.cn/mirror/argoproj/argocd:v1.8.2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-application-controller
        image: 508085692393.dkr.ecr.cn-northwest-1.amazonaws.com.cn/mirror/argoproj/argocd:v1.8.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      containers:
      - name: redis
        image: 508085692393.dkr.ecr.cn-northwest-1.amazonaws.com.cn/mirror/redis:5.0.10-alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-notifications-controller
        image: 508085692393.dkr.ecr.cn-northwest-1.amazonaws.com.cn/mirror/argoprojlabs/argocd-notifications:v1.0.1